#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::sync::atomic::{AtomicBool, Ordering};
use std::time::Duration;

use windows::Win32::Foundation::{HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
use windows::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, DispatchMessageW, GetMessageW, SetWindowsHookExW, TranslateMessage,
    UnhookWindowsHookEx, HC_ACTION, HHOOK, KBDLLHOOKSTRUCT, MSG, WH_KEYBOARD_LL, WM_KEYDOWN,
    WM_SYSKEYDOWN,
};
use windows::Win32::System::Threading::{GetCurrentThread, SetThreadPriority, THREAD_PRIORITY_TIME_CRITICAL};

mod helpers;
mod keyboard_event_handlers;
mod state;

use helpers::{KEYBOARDMANAGER_INJECTED_FLAG, KEYBOARDMANAGER_SUPPRESS_FLAG};
use state::State;

// Global state — key mapping
static G_STATE: OnceLock<Arc<Mutex<State>>> = OnceLock::new();
static mut G_HOOK: HHOOK = HHOOK(std::ptr::null_mut());
static mut G_HOOK_COPY: HHOOK = HHOOK(std::ptr::null_mut());
static RUNNING: AtomicBool = AtomicBool::new(true);
static ENABLED: AtomicBool = AtomicBool::new(true);

fn get_state() -> Arc<Mutex<State>> {
    G_STATE.get_or_init(|| Arc::new(Mutex::new(State::new()))).clone()
}

fn set_mappings(m: HashMap<u32, u32>) {
    let st = get_state();
    let mut s = st.lock().unwrap();
    s.clear();
    for (src, dst) in m {
        // AddSingleKeyRemap: exact VK->VK, no OEM expansion
        // Generic modifiers are kept as-is; lookup is exact.
        // No scan-priority improvisation.
        s.add_single_key_remap(src, dst);
    }
}

unsafe extern "system" fn hook(n: i32, w: WPARAM, l: LPARAM) -> LRESULT {
    if n != HC_ACTION as i32 {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }
    let kb = &*(l.0 as *const KBDLLHOOKSTRUCT);
    let vk_raw = kb.vkCode;
    let flags = kb.flags;
    let extra = kb.dwExtraInfo as usize;
    let is_extended = (flags.0 & 0x01) != 0; // LLKHF_EXTENDED = 0x01
    let mut vk = helpers::encode_numpad_origin(vk_raw, is_extended);

    // If SUPPRESS_FLAG, suppress immediately
    if extra == KEYBOARDMANAGER_SUPPRESS_FLAG {
        return LRESULT(1);
    }
    // If generated by engine (INJECTED_FLAG), pass through
    if (extra & KEYBOARDMANAGER_INJECTED_FLAG) != 0 {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }

    // file-watch style F6 global toggle — exact handling, no file polling
    // VK_F6 = 0x75 — on keydown, toggle ENABLED and suppress the original F6
    if vk_raw == 0x75 && (w.0 == WM_KEYDOWN as usize || w.0 == WM_SYSKEYDOWN as usize) {
        let new_val = !ENABLED.load(Ordering::SeqCst);
        ENABLED.store(new_val, Ordering::SeqCst);
        // Notify UI via file so Tauri's get_engine_enabled polling sees the toggle
        // This is Lefty-specific notification, not Lefty file polling
        if let Ok(appdata) = env::var("APPDATA") {
            let p = PathBuf::from(appdata).join("Lefty").join("f6_toggle.txt");
            let _ = fs::create_dir_all(p.parent().unwrap());
            let _ = fs::write(&p, if new_val { b"1" } else { b"0" });
        }
        return LRESULT(1);
    }

    if !ENABLED.load(Ordering::SeqCst) {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }

    let is_key_down = w.0 == WM_KEYDOWN as usize || w.0 == WM_SYSKEYDOWN as usize;

    // native low-level dispatch: HandleSingleKeyRemapEvent only (single-key path).
    // We keep hook minimal — no OEM expansion, no scan priority, no debug logs.
    let result = {
        let st = get_state();
        let mut guard = st.lock().unwrap();
        keyboard_event_handlers::handle_single_key_remap(&mut vk, is_key_down, extra, &mut guard)
    };

    // handle_single_key_remap returns Some if handled (including disabled suppress)
    // It already performed SendInput for target; we just need to suppress original.
    if result.is_some() {
        return LRESULT(1);
    }

    CallNextHookEx(G_HOOK_COPY, n, w, l)
}

fn mappings_path() -> PathBuf {
    let args: Vec<String> = env::args().collect();
    for i in 0..args.len() {
        if args[i] == "--mappings" && i + 1 < args.len() {
            return PathBuf::from(&args[i + 1]);
        }
    }
    if let Ok(p) = env::var("LEFTY_MAPPINGS") {
        return PathBuf::from(p);
    }
    if let Ok(a) = env::var("APPDATA") {
        return PathBuf::from(a).join("Lefty").join("engine_mappings.json");
    }
    PathBuf::from("engine_mappings.json")
}

fn load(p: &Path) -> Option<HashMap<u32, u32>> {
    let s = fs::read_to_string(p).ok()?;
    let m: HashMap<String, u32> = serde_json::from_str(&s).ok()?;
    let mut o = HashMap::new();
    for (k, v) in m {
        if let Ok(ki) = k.parse::<u32>() {
            o.insert(ki, v);
        }
    }
    Some(o)
}

fn parent_pid_from_args() -> Option<u32> {
    let args: Vec<String> = env::args().collect();
    for i in 0..args.len() {
        if args[i] == "--parent-pid" && i + 1 < args.len() {
            if let Ok(pid) = args[i + 1].parse::<u32>() {
                return Some(pid);
            }
        }
    }
    None
}

fn main() {
    // Init state
    let _ = get_state();
    let mp = mappings_path();
    if mp.exists() {
        if let Some(m) = load(&mp) {
            set_mappings(m);
        }
    }
    // TIME_CRITICAL — high priority
    unsafe {
        let _ = SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);
    }

    let hook = unsafe { SetWindowsHookExW(WH_KEYBOARD_LL, Some(hook), HINSTANCE(std::ptr::null_mut()), 0) }
        .unwrap();
    unsafe {
        G_HOOK = hook;
        G_HOOK_COPY = hook;
    }

    // Watch mappings file — file-watch style settings event (file watch, not F6 polling)
    let mp2 = mp.clone();
    std::thread::spawn(move || {
        let mut last = fs::metadata(&mp2).and_then(|m| m.modified()).ok();
        loop {
            std::thread::sleep(Duration::from_millis(300));
            if let Ok(md) = fs::metadata(&mp2) {
                if let Ok(mt) = md.modified() {
                    if Some(mt) != last {
                        last = Some(mt);
                        if let Some(m) = load(&mp2) {
                            set_mappings(m);
                        }
                    }
                }
            }
            if !RUNNING.load(Ordering::SeqCst) {
                break;
            }
        }
    });

    // Parent PID is parsed for compatibility with --parent-pid (native style) but not used to kill engine;
    // Tauri's stop_engine kills the child explicitly. Keeping hook alive even if parent alive check is optional.
    let _ = parent_pid_from_args();

    let mut msg = MSG::default();
    unsafe {
        while RUNNING.load(Ordering::SeqCst) {
            let r = GetMessageW(&mut msg, HWND(std::ptr::null_mut()), 0, 0);
            if r.0 == 0 || r.0 == -1 {
                break;
            }
            let _ = TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
        let _ = UnhookWindowsHookEx(G_HOOK);
    }
}
