#![cfg_attr(not(debug_assertions), windows_subsystem = "windows")]

use std::collections::HashMap;
use std::env;
use std::fs;
use std::path::{Path, PathBuf};
use std::sync::{Arc, Mutex, OnceLock};
use std::sync::atomic::{AtomicBool, AtomicU32, Ordering};
use std::time::Duration;

use windows::Win32::Foundation::{HINSTANCE, HWND, LPARAM, LRESULT, WPARAM};
use windows::Win32::UI::WindowsAndMessaging::{
    CallNextHookEx, DispatchMessageW, GetMessageW, SetWindowsHookExW, TranslateMessage,
    UnhookWindowsHookEx, HC_ACTION, HHOOK, KBDLLHOOKSTRUCT, MSG, WH_KEYBOARD_LL, WM_KEYDOWN,
    WM_SYSKEYDOWN,
};
use windows::Win32::System::Threading::{GetCurrentThread, SetThreadPriority, THREAD_PRIORITY_TIME_CRITICAL};

mod helpers;
mod keyboard_event_handlers;
mod state;

use helpers::{KEYBOARDMANAGER_INJECTED_FLAG, KEYBOARDMANAGER_SUPPRESS_FLAG};
use state::State;

// Global state — key mapping
static G_STATE: OnceLock<Arc<Mutex<State>>> = OnceLock::new();
static mut G_HOOK: HHOOK = HHOOK(std::ptr::null_mut());
static mut G_HOOK_COPY: HHOOK = HHOOK(std::ptr::null_mut());
static RUNNING: AtomicBool = AtomicBool::new(true);
static ENABLED: AtomicBool = AtomicBool::new(false);
static HOTKEY_VK: AtomicU32 = AtomicU32::new(0x75);

fn get_state() -> Arc<Mutex<State>> {
    G_STATE.get_or_init(|| Arc::new(Mutex::new(State::new()))).clone()
}

fn set_mappings(m: HashMap<u32, u32>) {
    let st = get_state();
    let mut s = st.lock().unwrap();
    s.clear();
    for (src, dst) in m {
        // AddSingleKeyRemap: exact VK->VK, no OEM expansion
        // Generic modifiers are kept as-is; lookup is exact.
        // No scan-priority improvisation.
        s.add_single_key_remap(src, dst);
    }
}

unsafe extern "system" fn hook(n: i32, w: WPARAM, l: LPARAM) -> LRESULT {
    if n != HC_ACTION as i32 {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }
    let kb = &*(l.0 as *const KBDLLHOOKSTRUCT);
    let vk_raw = kb.vkCode;
    let flags = kb.flags;
    let extra = kb.dwExtraInfo as usize;
    let is_extended = (flags.0 & 0x01) != 0; // LLKHF_EXTENDED = 0x01
    let mut vk = helpers::encode_numpad_origin(vk_raw, is_extended);

    // If SUPPRESS_FLAG, suppress immediately
    if extra == KEYBOARDMANAGER_SUPPRESS_FLAG {
        return LRESULT(1);
    }
    // If generated by engine (INJECTED_FLAG), pass through
    if (extra & KEYBOARDMANAGER_INJECTED_FLAG) != 0 {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }

    // Custom hotkey (default F6) — native low-level, instant toggle without blocking I/O
    let hotkey = HOTKEY_VK.load(Ordering::SeqCst);
    if vk_raw == hotkey && (w.0 == WM_KEYDOWN as usize || w.0 == WM_SYSKEYDOWN as usize) {
        let new_val = !ENABLED.load(Ordering::SeqCst);
        ENABLED.store(new_val, Ordering::SeqCst);
        // Async write to avoid blocking the hook (prevents perceived delay on first F6)
        if let Ok(appdata) = env::var("APPDATA") {
            let p = PathBuf::from(appdata).join("Lefty").join("f6_toggle.txt");
            let val = new_val;
            std::thread::spawn(move || {
                let _ = fs::create_dir_all(p.parent().unwrap());
                let _ = fs::write(&p, if val { b"1" } else { b"0" });
            });
        }
        return LRESULT(1);
    }
    if vk_raw == hotkey {
        return LRESULT(1);
    }

    if !ENABLED.load(Ordering::SeqCst) {
        return CallNextHookEx(G_HOOK_COPY, n, w, l);
    }

    let is_key_down = w.0 == WM_KEYDOWN as usize || w.0 == WM_SYSKEYDOWN as usize;

    // native low-level dispatch: HandleSingleKeyRemapEvent only (single-key path).
    // We keep hook minimal — no OEM expansion, no scan priority, no debug logs.
    let result = {
        let st = get_state();
        let mut guard = st.lock().unwrap();
        keyboard_event_handlers::handle_single_key_remap(&mut vk, is_key_down, extra, &mut guard)
    };

    // handle_single_key_remap returns Some if handled (including disabled suppress)
    // It already performed SendInput for target; we just need to suppress original.
    if result.is_some() {
        return LRESULT(1);
    }

    CallNextHookEx(G_HOOK_COPY, n, w, l)
}

fn mappings_path() -> PathBuf {
    let args: Vec<String> = env::args().collect();
    for i in 0..args.len() {
        if args[i] == "--mappings" && i + 1 < args.len() {
            return PathBuf::from(&args[i + 1]);
        }
    }
    if let Ok(p) = env::var("LEFTY_MAPPINGS") {
        return PathBuf::from(p);
    }
    if let Ok(a) = env::var("APPDATA") {
        return PathBuf::from(a).join("Lefty").join("engine_mappings.json");
    }
    PathBuf::from("engine_mappings.json")
}

fn load(p: &Path) -> Option<HashMap<u32, u32>> {
    let s = fs::read_to_string(p).ok()?;
    let m: HashMap<String, u32> = serde_json::from_str(&s).ok()?;
    let mut o = HashMap::new();
    for (k, v) in m {
        if let Ok(ki) = k.parse::<u32>() {
            o.insert(ki, v);
        }
    }
    Some(o)
}

fn parent_pid_from_args() -> Option<u32> {
    let args: Vec<String> = env::args().collect();
    for i in 0..args.len() {
        if args[i] == "--parent-pid" && i + 1 < args.len() {
            if let Ok(pid) = args[i + 1].parse::<u32>() {
                return Some(pid);
            }
        }
    }
    None
}

fn main() {
    // Init state
    let _ = get_state();
    // Init ENABLED from f6_toggle.txt (default paused)
    let f6_path = if let Ok(a) = env::var("APPDATA") { PathBuf::from(a).join("Lefty").join("f6_toggle.txt") } else { PathBuf::from("f6_toggle.txt") };
    if let Ok(s) = fs::read_to_string(&f6_path) {
        ENABLED.store(s.trim() == "1", Ordering::SeqCst);
    } else {
        ENABLED.store(false, Ordering::SeqCst);
    }
    let f6_path2 = f6_path.clone();
    std::thread::spawn(move ||{
        let mut last = fs::read_to_string(&f6_path2).unwrap_or("0".to_string());
        loop{
            std::thread::sleep(Duration::from_millis(35));
            if let Ok(s) = fs::read_to_string(&f6_path2) {
                if s.trim() != last.trim() {
                    last = s.clone();
                    ENABLED.store(s.trim() == "1", Ordering::SeqCst);
                }
            }
            if !RUNNING.load(Ordering::SeqCst){ break; }
        }
    });
    let mp = mappings_path();
    if mp.exists() {
        if let Some(m) = load(&mp) {
            set_mappings(m);
        }
    }
    // TIME_CRITICAL — high priority
    unsafe {
        let _ = SetThreadPriority(GetCurrentThread(), THREAD_PRIORITY_TIME_CRITICAL);
    }

    let hook = unsafe { SetWindowsHookExW(WH_KEYBOARD_LL, Some(hook), HINSTANCE(std::ptr::null_mut()), 0) }
        .unwrap();
    unsafe {
        G_HOOK = hook;
        G_HOOK_COPY = hook;
    }

    // Watch mappings file — file-watch style settings event (file watch, not F6 polling)
    let mp2 = mp.clone();
    std::thread::spawn(move ||{
        let mut last=fs::metadata(&mp2).and_then(|m| m.modified()).ok();
        loop{
            std::thread::sleep(Duration::from_millis(40));
            if let Ok(md)=fs::metadata(&mp2){
                if let Ok(mt)=md.modified(){
                    if Some(mt)!=last{
                        last=Some(mt);
                        if let Some(m)=load(&mp2){ set_mappings(m); }
                    }
                }
            }
            if !RUNNING.load(Ordering::SeqCst){ break; }
        }
    });
    // Watch hotkey file for custom hotkey (F6 default)
    let hotkey_path = if let Ok(a) = env::var("APPDATA") { PathBuf::from(a).join("Lefty").join("hotkey.txt") } else { PathBuf::from("hotkey.txt") };
    // Helper to map hotkey name to VK (any key, not just F6-F12)
    fn hotkey_str_to_vk(s: &str) -> Option<u32> {
        let n = s.trim().to_uppercase();
        // Try direct VK_MAP-like mapping for common keys
        let vk = match n.as_str() {
            "A"=>0x41, "B"=>0x42, "C"=>0x43, "D"=>0x44, "E"=>0x45, "F"=>0x46, "G"=>0x47, "H"=>0x48, "I"=>0x49, "J"=>0x4A, "K"=>0x4B, "L"=>0x4C, "M"=>0x4D, "N"=>0x4E, "O"=>0x4F, "P"=>0x50, "Q"=>0x51, "R"=>0x52, "S"=>0x53, "T"=>0x54, "U"=>0x55, "V"=>0x56, "W"=>0x57, "X"=>0x58, "Y"=>0x59, "Z"=>0x5A,
            "0"=>0x30, "1"=>0x31, "2"=>0x32, "3"=>0x33, "4"=>0x34, "5"=>0x35, "6"=>0x36, "7"=>0x37, "8"=>0x38, "9"=>0x39,
            "F1"=>0x70, "F2"=>0x71, "F3"=>0x72, "F4"=>0x73, "F5"=>0x74, "F6"=>0x75, "F7"=>0x76, "F8"=>0x77, "F9"=>0x78, "F10"=>0x79, "F11"=>0x7A, "F12"=>0x7B, "F13"=>0x7C, "F14"=>0x7D, "F15"=>0x7E, "F16"=>0x7F, "F17"=>0x80, "F18"=>0x81, "F19"=>0x82, "F20"=>0x83,
            "ESC"=>0x1B, "SPACE"=>0x20, "ENTER"=>0x0D, "TAB"=>0x09, "BACKSPACE"=>0x08, "CAPSLOCK"=>0x14, "CAPS"=>0x14,
            "SHIFT"=>0x10, "LSHIFT"=>0xA0, "RSHIFT"=>0xA1, "CTRL"=>0x11, "LCTRL"=>0xA2, "RCTRL"=>0xA3, "ALT"=>0x12, "LALT"=>0xA4, "RALT"=>0xA5, "LWIN"=>0x5B, "RWIN"=>0x5C,
            "UP"=>0x26, "DOWN"=>0x28, "LEFT"=>0x25, "RIGHT"=>0x27, "INSERT"=>0x2D, "DELETE"=>0x2E, "HOME"=>0x24, "END"=>0x23, "PAGEUP"=>0x21, "PAGEDOWN"=>0x22, "NUMLOCK"=>0x90, "SCROLLLOCK"=>0x91, "PRINTSCREEN"=>0x2C, "PAUSE"=>0x13,
            "OEM_1"=>0xBA, "OEM_PLUS"=>0xBB, "OEM_COMMA"=>0xBC, "OEM_MINUS"=>0xBD, "OEM_PERIOD"=>0xBE, "OEM_2"=>0xBF, "OEM_3"=>0xC0, "OEM_4"=>0xDB, "OEM_5"=>0xDC, "OEM_6"=>0xDD, "OEM_7"=>0xDE, "OEM_8"=>0xDF, "OEM_102"=>0xE2,
            "Ñ"=>0xBA, "´"=>0xDB, "Ç"=>0xDE, "¨"=>0xDB,
            _ => {
                if n.starts_with("0X") {
                    if let Ok(v) = u32::from_str_radix(n.trim_start_matches("0X"), 16) { return Some(v); }
                }
                if let Ok(v) = n.parse::<u32>() { return Some(v); }
                if n.starts_with("VK_") {
                    let rest = n.trim_start_matches("VK_");
                    if let Ok(v) = u32::from_str_radix(rest, 16) { return Some(v); }
                    if let Ok(v) = rest.parse::<u32>() { return Some(v); }
                }
                return None;
            }
        };
        Some(vk)
    }
    // Load initial hotkey (any key)
    if let Ok(s) = fs::read_to_string(&hotkey_path) {
        if let Some(vk) = hotkey_str_to_vk(&s) {
            HOTKEY_VK.store(vk, Ordering::SeqCst);
        }
    }
    let hotkey_path2 = hotkey_path.clone();
    std::thread::spawn(move ||{
        let mut last_hotkey = fs::read_to_string(&hotkey_path2).unwrap_or("F6".to_string());
        loop{
            std::thread::sleep(Duration::from_millis(80));
            if let Ok(s) = fs::read_to_string(&hotkey_path2) {
                let n = s.trim().to_uppercase();
                if n != last_hotkey.trim().to_uppercase() {
                    last_hotkey = s.clone();
                    if let Some(v) = hotkey_str_to_vk(&n) {
                        HOTKEY_VK.store(v, Ordering::SeqCst);
                    }
                }
            }
            if !RUNNING.load(Ordering::SeqCst){ break; }
        }
    });

    // Parent PID is parsed for compatibility with --parent-pid (native style) but not used to kill engine;
    // Tauri's stop_engine kills the child explicitly. Keeping hook alive even if parent alive check is optional.
    let _ = parent_pid_from_args();

    let mut msg = MSG::default();
    unsafe {
        while RUNNING.load(Ordering::SeqCst) {
            let r = GetMessageW(&mut msg, HWND(std::ptr::null_mut()), 0, 0);
            if r.0 == 0 || r.0 == -1 {
                break;
            }
            let _ = TranslateMessage(&msg);
            DispatchMessageW(&msg);
        }
        let _ = UnhookWindowsHookEx(G_HOOK);
    }
}
